[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 20

[[main]]
  name = "Leon Sans"
  url = "/leonsans"
  weight = 30

[[main]]
  name = "Demo Pages"
  url = "/demo"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/ChristineTham"
  weight = 50

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/christham/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/chris1tham"
  weight = 30
