title = "Travels"
titleSeparator = "-"
titleAddition = "Through A Lens"
description = "Hugo starter helping you build modern websites."

images = ["images/banner.jpg"]

twitterSite = "@chris1tham"
twitterCreator = "@chris1tham"
facebookAuthor = "chris1tham"
facebookPublisher = "chris1tham"
ogLocale = "en_AU"

schemaType = "Organization"
schemaLogo = "logo-hyas.png"
schemaTwitter = "https://twitter.com/chris1tham"
schemaLinkedIn = "https://www.linkedin.com/in/christham/"
schemaGitHub = "https://github.com/ChristineTham"
schemaSection = "blog"

siteLinksSearchBox = false

themeColor = "#fff"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [1000, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"


# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"

alert = false
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"

bannerImage = "images/banner.jpg"
